# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
permissions:
  contents: read

jobs:

  build:
    strategy:
      matrix:
        go-version: [1.19.x] #[1.16.x, 1.17.x, 1.19.x]
        os: [ubuntu-latest] #[ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/cache@v3
      with:
        path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
        key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-
    - uses: actions/checkout@v3

    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: abstract-factory
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: adapter
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: bridge
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: builder
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: chain-of-responsibility
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: command
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: composite
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: decorator
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: facade
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: factory-method
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: flyweight
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: iterator
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: mediator
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: memento
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: observer
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: prototype
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: proxy
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: singleton-01
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: singleton-02
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: state
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: strategy
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: template-method
    - name: Run golangci-lint adapter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: visitor